from graph.state import TravelState

from agents.research_agent import (
    research_destination
)

from agents.budget_agent import (
    generate_budget
)

from agents.hotel_agent import (
    recommend_hotels
)

from agents.itinerary_agent import (
    generate_itinerary_from_state
)

from agents.risk_agent import (
    assess_risk
)

from services.travel_package_builder import (
    build_package
)

import logging

from human_loop.approval_manager import (
    request_approval
)

logger = logging.getLogger(__name__)

# Importing the graph builder to construct the workflow graph
def research_node(
        state: TravelState
):

    state["research_report"] = (
        research_destination(
            state["destination"]
        )
    )

    return state

# Budget node to generate a budget report based on the destination, budget, and duration
def budget_node(
        state: TravelState
):

    state["budget_report"] = (
        generate_budget(
            state["destination"],
            state["budget"],
            state["duration"]
        )
    )

    return state

# Hotel node to recommend hotels based on the destination and budget
def hotel_node(
        state: TravelState
):

    state["hotel_report"] = (
        recommend_hotels(
            state["destination"],
            state["budget"]
        )
    )

    return state

# Itinerary node to create a day-wise itinerary for the trip based on the destination, duration, and budget
def itinerary_node(
        state: TravelState
):

    state["itinerary_report"] = (
        generate_itinerary_from_state(
            state
        )
    )

    return state

# Risk assessment node to evaluate potential risks associated with the destination and travel plans
def risk_node(
        state: TravelState
):

    state["risk_report"] = (
        assess_risk(
            state["destination"]
        )
    )

    return state

# Supervisor node to create the final travel package based on the reports generated by the previous nodes
def supervisor_node(
        state
):

    state["final_package"] = (
        build_package(
            state
        )
    )

    return state

# Adding an approval node to the workflow to get human approval for the final travel package
def approval_node(state: TravelState):
    
    decision = request_approval()

    logger.info(f"Approval Decision: {decision}")

    state["approval_status"] = (decision)
    
    return state